server:
  port: 8080


spring:
  application:
    name: admin-center
  datasource:
    url: jdbc:mysql://localhost:3306/admin_center?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Lc123456@

mybatis:
  mapper-locations: classpath:mapper/*.xml
