server:
  port: 8808

spring:
  application:
    name: admin-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth-center?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Lc123456@


  redis:
    host: 127.0.0.1
    port: 6379

debug: true
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

my-shiro:
  max-batch-insert-num: 10
  shiro-properties:
    sessiotimeout: PT86400s
    enable-redis-cache: true
    login-url: /login
    success-url: /index
    unauthorized-url: /unauthorized
    logout-url: /logout
    anon-url: /test/**,/febs/**,/img/**,/layui/**,/json/**,/images/captcha,/register

